### ISSUE TITLE
Creating a decoder mixin

### ISSUE THREAD

**Issue by dlord781** [jaimegildesagredo/booby#27]
What would be the best way to create my own decoder mixin? I would like to change the name of the field during decoding to match an API's custom field value instead of the real name. 

Is this possible?

**Comment by jaimegildesagredo** [comment]
Hi @dlord781 and sorry for the delay.

To change the field name in encoding/decoding you could use the `name` argument in fields [[0]].

```python
from booby import Model, fields

class Foo(Model):
    some_name = fields.Field(name='somName')

Foo(some_name='bar).encode()   # {'someName': 'bar'}
```

If you need a custom encoder/decoder for a custom behavior you can create a base model, or some mixing classes with `endcode` and `decode` methods [[1]]. Also you can pass encoders to a field [[2]].

[0]: http://booby.readthedocs.org/en/v0.7.0/fields.html#fields.Field
[1]: https://github.com/jaimegildesagredo/booby/blob/master/booby/mixins.py#L18
[2]: https://github.com/jaimegildesagredo/booby/blob/master/booby/fields.py#L130
